#' Compute UBMI Object(s)
#'
#' @param output_path String form of directory of where to save data (can be 
#' NULL if save_data = FALSE)
#' @param cleaned_data cleaned data object generated by a cleaning script (of 
#' type list of lists)
#' @param save_data whether to save the data (to the output directory)
#' @param plot_data whether to generate plots (plots will be saved if save_data 
#' = TRUE)
#'
#' @return a list of ubmi objects, sorted by silhouette score
#' @return if save_data = TRUE, also returns file path of saved location
#' 
compute_ubmi <- function(cleaned_data, output_path, save_data = TRUE, plot_data = TRUE) {
  library(tools)
  library(ubmi)
  library(patchwork)
  library(ggplot2)
  
  if (save_data) {
    # Create the main folder if it doesn't exist
    if (!dir.exists(output_path)) {
      dir.create(output_path)
    }
    
    timely_path <- file.path(output_path, format(Sys.time(), "%Y-%m-%d %H-%M-%S"))
    dir.create(timely_path)
  }
  
  # Initialize lists to store silhouette scores and UBMI objects
  silhouette_scores <- list()
  ubmi_results <- list()
  
  for (cancer in names(cleaned_data)) {
    # Extract Data
    exp <- cleaned_data[[cancer]][["exp"]]
    methy <- cleaned_data[[cancer]][["methy"]]
    mirna <- cleaned_data[[cancer]][["mirna"]]
    # surv <- cleaned_data[[cancer]][["survival"]]
    
    multi_omic_data <- list(exp, methy, mirna)
    multi_omic_data <- multi_omic_data[!sapply(multi_omic_data, is.null)]
    
    cleaned_ubmi <- ubmi(multi_omic_data, combine_omics = TRUE)
    
    silhouette_scores[[cancer]] <- cleaned_ubmi@silhouette_score
    ubmi_results[[cancer]] <- cleaned_ubmi
    
    # Generate plots on UBMI object
    if (plot_data) {
      # Factor Plot
      factor_plot <- ubmi::plot_factors(cleaned_ubmi) + 
        ggtitle(toTitleCase(paste0(cancer, ": Factor Plot")))
      
      # Metagene Plot
      metagene_plot <- ubmi::plot_metagenes(cleaned_ubmi) + 
        ggtitle(toTitleCase(paste0(cancer, ": Metagenes")))
      
      # UBMI Grid Plot (summary)
      ubmi_grid_plot <- ubmi::plot_ubmi_grid(cleaned_ubmi) + 
        plot_annotation(title = (toTitleCase(paste(cancer, ": UBMI Grid"))))
    }
    
    # Save plots to output file
    if (save_data & plot_data) {
      subfolder_path <- file.path(timely_path, cancer)
      
      # Create the subfolder if it doesn't exist
      if (!dir.exists(subfolder_path)) {
        dir.create(subfolder_path)
      }
      
      # Save the plots in the subfolder
      ggsave(file.path(subfolder_path, paste0(cancer, "_factor_plot.png")), plot = factor_plot, width = 10, height = 6)
      ggsave(file.path(subfolder_path, paste0(cancer, "_metagene_plot.png")), plot = metagene_plot, width = 10, height = 6)
      ggsave(file.path(subfolder_path, paste0(cancer, "_ubmi_grid_plot.png")), plot = ubmi_grid_plot, width = 15, height = 9)
      
      # Print statements to confirm that the plots are generated and saved
      print(paste("Plots saved for:", cancer))
    }
    
    if (plot_data & !save_data) {
      factor_plot
      survival_plot
      metagene_plot
      ubmi_grid_plot
    }
  }
  
  # Create a data frame with silhouette scores
  silhouette_scores_df <- data.frame(
    Cancer = names(silhouette_scores),
    SilhouetteScore = unlist(silhouette_scores)
  )
  
  # Sort the data frame by silhouette score
  silhouette_scores_df <- silhouette_scores_df[order(silhouette_scores_df$SilhouetteScore, decreasing = TRUE), ]
  
  # Print the ranking
  print(silhouette_scores_df)
  
  # Store the UBMI objects in a named list
  sorted_ubmi_results <- ubmi_results[silhouette_scores_df$Cancer]
  
  if (save_data) {
    write.csv(silhouette_scores_df, file.path(timely_path, "silhouettes"), row.names = FALSE)
    save(sorted_ubmi_results, file = file.path(timely_path, "ubmi_results"))
  }
  
  if (!save_data) {
    return (c(sorted_ubmi_results, NULL))
  } else {
    return (c(sorted_ubmi_results, timely_path))
  }
}

## ================================================
## ============ Example Implementation ============
## ================================================
# cancers <- c("breast", "colon")
# datasets <- c("exp", "methy", "mirna", "survival")
# base_path <- "/Users/home/Desktop/Cancer Datasets"
# output_path <- "/Users/home/TCGA/Cancer Plots"
# source("Overall Cleaning Script.R")
# cleaned_data <- extract_and_clean_data(cancers, datasets, base_path)
# sorted_ubmi_results <- compute_ubmi(cleaned_data, output_path)